// Code generated by go-bindata.
// sources:
// routes/index/favicon.ico
// routes/index/index.html
// routes/index/main.css
// routes/index/main.js
// DO NOT EDIT!

package routes

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"github.com/elazarl/go-bindata-assetfs"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _faviconIco = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func faviconIcoBytes() ([]byte, error) {
	return bindataRead(
		_faviconIco,
		"favicon.ico",
	)
}

func faviconIco() (*asset, error) {
	bytes, err := faviconIcoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "favicon.ico", size: 0, mode: os.FileMode(436), modTime: time.Unix(1529589120, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _indexHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x52\x4d\x8f\xd3\x30\x10\xbd\xf7\x57\x0c\x73\x26\xb5\x7a\x43\x2b\xdb\x62\xb5\xac\x00\x09\x69\x11\xa2\x12\x2b\xc4\xc1\x4d\xa6\xb5\xc1\x89\x8d\x3d\x69\x89\x96\xfe\x77\x94\x2f\x92\x3d\x6c\x2e\xc9\x9b\x97\xf7\xfc\xf4\xc6\xf2\xd5\xbb\x87\xbb\xaf\x8f\x9f\xef\xc1\x72\xed\xf5\x46\xce\x2f\x32\x95\xde\x00\x00\xc8\x9a\xd8\x40\x69\x4d\xca\xc4\x0a\x5b\x3e\x16\x6f\x10\xc4\x9a\xb4\xcc\xb1\xa0\xdf\xad\x3b\x2b\xfc\x56\xec\x6f\x8b\xbb\x50\x47\xc3\xee\xe0\x09\xa1\x0c\x0d\x53\xc3\x0a\x3f\xde\x2b\xaa\x4e\x84\x93\x92\x1d\x7b\xd2\x8f\x26\xb7\x99\x92\x14\x23\x5c\x99\x36\xa6\x26\x85\x67\x47\x97\x18\x12\xaf\x7c\x2e\xae\x62\xab\x2a\x3a\xbb\x92\x8a\x01\xbc\x06\xd7\x38\x76\xc6\x17\xb9\x34\x9e\xd4\x6e\x3e\xc3\xbb\xe6\x17\x24\xf2\x0a\x33\x77\x9e\xb2\x25\x62\x04\xee\x22\x29\x64\xfa\xc3\xa2\xcc\x19\xc1\x26\x3a\x2a\xac\x8d\x6b\xb6\x03\x16\x7a\x23\xc5\x58\x80\x3c\x84\xaa\x9b\x53\x19\xd7\x8c\x9f\x03\xb4\x3b\xdd\xcd\xe1\xed\x6e\x21\x3e\x90\xf7\x01\xbe\xc3\xd3\x13\x6c\xf7\xb7\x70\xbd\xc2\x8f\x45\x74\x0c\xa9\x5e\x7e\xed\x9f\xfd\x97\x4f\x37\xcf\x06\xd2\x35\xb1\xe5\x55\x48\x84\xe8\x4d\x49\x36\xf8\x8a\x92\xc2\xde\xb7\x0a\x7d\x18\xb8\x5e\x11\x5c\xa5\xb0\x4d\x1e\xf5\xcb\x26\x87\x96\x39\x34\x08\x67\xe3\x5b\x52\xf8\xfe\x61\x54\x9d\xc2\x4a\x24\xc5\xf3\x68\x0b\x11\xb5\x34\x53\x45\xfd\x9e\xf3\x8d\x10\x27\xc7\xb6\x3d\x6c\xcb\x50\x8b\x4b\x3a\xfa\x4e\x4c\x45\xa0\x7e\xfb\xbf\x12\xa3\xe1\x2f\x0c\xac\x14\x71\x6a\x50\x2c\x15\xca\x63\x08\x4c\x69\x26\x66\x24\xc5\x58\xb8\xcc\x65\x72\x91\x21\xa7\x72\xda\xcc\xcf\x8c\x5a\x8a\x71\x3c\xec\xa7\xbf\xa7\xff\x02\x00\x00\xff\xff\x62\xdd\x30\xde\xbe\x02\x00\x00")

func indexHtmlBytes() ([]byte, error) {
	return bindataRead(
		_indexHtml,
		"index.html",
	)
}

func indexHtml() (*asset, error) {
	bytes, err := indexHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "index.html", size: 702, mode: os.FileMode(436), modTime: time.Unix(1529600805, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mainCss = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2c\xce\xcd\xaa\xc2\x30\x10\xc5\xf1\x7d\x9f\x62\x36\x77\x73\xa1\x50\xc4\x4d\xe3\xd3\xe4\x63\x8c\x83\x69\x4e\x49\xa7\x58\x11\xdf\x5d\x9a\x64\xfb\xcf\xf9\x85\x71\x08\x6f\xfa\x0c\x44\x44\xce\xfa\x67\x2c\xd8\x73\x18\x3d\x12\x8a\xa1\x80\x10\xb9\xb8\xb4\xf3\xad\x2e\x7a\xb6\x49\x3c\xb7\xfa\x1d\x86\xff\xce\x17\x5b\xa2\xe4\x51\xb1\x1a\xba\x4e\xeb\xd1\x88\xf2\xa1\xa3\x4d\x12\xb3\x21\xcf\x59\xb9\x54\xb4\x58\xc9\x8d\xd5\xfd\x65\xfa\xab\xf9\x0e\x28\x97\xf6\xb0\x62\x13\x15\x64\x43\xd6\x6d\x48\xbb\xf6\x23\x1c\x54\xb1\x74\x73\x86\x97\x04\x7d\x18\x9a\xe7\xf3\x8f\x5f\x00\x00\x00\xff\xff\x9c\xc1\x05\x0c\xd0\x00\x00\x00")

func mainCssBytes() ([]byte, error) {
	return bindataRead(
		_mainCss,
		"main.css",
	)
}

func mainCss() (*asset, error) {
	bytes, err := mainCssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "main.css", size: 208, mode: os.FileMode(436), modTime: time.Unix(1529598343, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mainJs = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x92\x41\x6b\xe3\x30\x14\x84\xef\xfe\x15\xb3\xbe\x44\x66\x17\x6f\x28\x3d\xd5\xe8\x12\x28\xb4\x90\xd2\x92\xa4\xd0\xab\x6b\xbf\x38\xa6\x8a\xe4\x4a\x4f\x69\x42\xf1\x7f\x2f\x4a\xe2\x26\x76\x4a\x75\x12\xcc\x37\xf3\x86\x27\x6d\x72\x8b\xca\x4c\x3c\xb3\xd1\x90\x28\x4d\xe1\xd7\xa4\x39\xad\x88\x6f\x15\x85\xeb\x64\x77\x5f\x8a\x51\x65\x46\x49\x16\x05\xda\x5b\x35\x31\xdb\xdf\x58\x6f\x55\x80\xa3\x2e\x37\x35\xba\x50\x75\xf1\x06\x89\xa5\xd7\x05\xd7\x46\x43\x24\xf8\x8c\x00\x20\x44\x2a\xa3\xab\xe7\xd9\x14\xf2\x18\x9e\x6e\x72\xe5\x29\xfb\xd6\xb7\x6b\xb5\x62\x6e\x20\xa1\xe9\x03\x2f\x0f\xd3\x3b\xe6\x66\x46\xef\x9e\x1c\x8b\xe4\xc0\x1d\x99\xd4\x34\xa4\x45\xfc\xf4\x38\x5f\xc4\xff\x10\xff\x8f\x87\xb2\xb6\x94\x97\x3b\xc7\x39\x53\xb1\xca\x75\x45\x3f\xb6\x0a\xa7\x5e\x42\x74\xb6\xbd\x69\x1e\x4c\x90\x12\xd7\xe7\x58\x57\xd2\x42\xe2\x84\xbb\xc6\x68\x47\x0b\xda\x72\xd6\x23\x0b\xa3\x9d\x51\x94\x96\xf4\xea\x2b\x61\x93\xbe\x7a\x3e\x32\x54\xf4\x0e\x7f\x24\xae\xc6\xe3\xe1\xc0\x70\x72\x45\x96\x2f\x22\x5a\x52\x8e\x2e\xe1\xf3\xc5\x42\xc2\x0e\x4c\x51\xff\xd6\x1e\xe4\x7e\xd9\xfd\x52\x6f\x10\xe3\x6f\xf7\x60\x83\xdd\x3a\xd2\xa5\x38\x49\x6d\x16\x45\xc7\xb1\x97\x1f\x40\x24\x87\x8e\xbc\xaa\x5d\xea\x48\x51\xb1\x7f\xc9\x36\xfb\x0a\x00\x00\xff\xff\x17\x55\x32\x2f\x91\x02\x00\x00")

func mainJsBytes() ([]byte, error) {
	return bindataRead(
		_mainJs,
		"main.js",
	)
}

func mainJs() (*asset, error) {
	bytes, err := mainJsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "main.js", size: 657, mode: os.FileMode(436), modTime: time.Unix(1529599804, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"favicon.ico": faviconIco,
	"index.html":  indexHtml,
	"main.css":    mainCss,
	"main.js":     mainJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"favicon.ico": &bintree{faviconIco, map[string]*bintree{}},
	"index.html":  &bintree{indexHtml, map[string]*bintree{}},
	"main.css":    &bintree{mainCss, map[string]*bintree{}},
	"main.js":     &bintree{mainJs, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

func assetFS() *assetfs.AssetFS {
	assetInfo := func(path string) (os.FileInfo, error) {
		return os.Stat(path)
	}
	for k := range _bintree.Children {
		return &assetfs.AssetFS{Asset: Asset, AssetDir: AssetDir, AssetInfo: assetInfo, Prefix: k}
	}
	panic("unreachable")
}
